name: Build Image

on:
  push:
    branches:
      - master
jobs:
  build-image-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: knatnetwork
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/knatnetwork/github-runner-kms-rs:latest-amd64
            knatnetwork/github-runner-kms-rs:latest-amd64


  build-image-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: knatnetwork
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}


      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.arm64
          platforms: linux/arm64
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/knatnetwork/github-runner-kms-rs:latest-arm64
            knatnetwork/github-runner-kms-rs:latest-arm64


  combine-two-images:
    runs-on: ubuntu-latest
    needs:
      - build-image-arm64
      - build-image-amd64
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: knatnetwork
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Get regctl
        run: |
          wget -q https://github.com/regclient/regclient/releases/download/v0.4.5/regctl-linux-amd64
          chmod +x regctl-linux-amd64

      - name: Combine two images on GHCR and sync to DockerHub
        run: |
          docker manifest create ghcr.io/knatnetwork/github-runner-kms-rs:latest --amend ghcr.io/knatnetwork/github-runner-kms-rs:latest-amd64 --amend ghcr.io/knatnetwork/github-runner-kms-rs:latest-arm64
          docker manifest push ghcr.io/knatnetwork/github-runner-kms-rs:latest

          ./regctl-linux-amd64 image copy ghcr.io/knatnetwork/github-runner-kms-rs:latest knatnetwork/github-runner:github-runner-kms-rs:latest -v info